spring:
  datasource:
    url: jdbc:postgresql://localhost/petclinic
    username: postgres
    password: 123321
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    problemdetails:
      enabled: true