spring:
  datasource:
    password: ${POSTGRES_PASS:petclinic}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
    username: ${POSTGRES_USER:petclinic}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
    change-log: classpath:/changelog/db.changelog-master.xml
  mvc:
    problemdetails:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath*:db/${database}/data.sql
      schema-locations: classpath*:db/${database}/schema.sql

database: postgres

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
        jdbc.core.StatementCreatorUtils: TRACE