CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);

CREATE TABLE IF NOT EXISTS types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_types PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(255),
   birth_date date,
   type_id INTEGER REFERENCES types (id),
   owner_id INTEGER REFERENCES owners (id)
);

CREATE TABLE IF NOT EXISTS specialties (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_specialties PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   CONSTRAINT pk_vets PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vet_specialties (
    vet_id INTEGER NOT NULL REFERENCES vets (id),
    specialty_id INTEGER NOT NULL REFERENCES specialties (id),
    UNIQUE (vet_id, specialty_id)
);

--ALTER TABLE vet_specialties ADD CONSTRAINT fk_vetspe_on_vet FOREIGN KEY (vet_id) REFERENCES vets (id);

CREATE TABLE IF NOT EXISTS visits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    visit_date date,
    description VARCHAR(255),
    pet_id INTEGER REFERENCES pets (id),
    CONSTRAINT pk_visits PRIMARY KEY (id)
);
--
---- changeset artyom:1730583978412-9
--ALTER TABLE pets ADD CONSTRAINT FK_PETS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES owners (id);
--
---- changeset artyom:1730583978412-10
--ALTER TABLE pets ADD CONSTRAINT FK_PETS_ON_TYPE FOREIGN KEY (type_id) REFERENCES types (id);
--
---- changeset artyom:1730583978412-11
--ALTER TABLE visits ADD CONSTRAINT FK_VISITS_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);
--
---- changeset artyom:1730583978412-12
--ALTER TABLE vet_specialties ADD CONSTRAINT fk_vetspe_on_specialty FOREIGN KEY (specialty_id) REFERENCES specialties (id);